services:
  cliente_pwa:
    image: mapezza-app-imagen:v1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_mapezza
    restart: always
    volumes:
      - ./mi_app:/var/www/html/
    ports:
      - "8081:80"